### ISSUE TITLE
Enhancement Needed: Completed steps

### ISSUE THREAD

**Issue by Korey** [Ludovicus/WoW-Pro-Guides#264]
I think it would be helpful if we could adjust at least the color of completed steps for quests. Personally, I would set it up to grey. It's a visual thing. Look at Blizzard's built-in tracker, it completely hides completed steps to avoid confusion and clutter.

This comes in play the most for quests that require you to do more than one task at the time.

**Comment by Ludovicus** [comment]
Completed steps are now detected and removed from view.
