### ISSUE TITLE
QO steps and Sticky steps

### ISSUE THREAD

**Issue by Crackerhead22** [Ludovicus/WoW-Pro-Guides#347]
It seems that when there is a sticky step that QO steps do not want to advance themselves off the list.  They check themselves off, but don't clear off.  I was not in combat either.  I noticed this when I put a sticky step in for "The Leaders at Jin'Alai" above the QO steps for "Breaking Through Jin'Alai".

**Comment by Ludovicus** [comment]
@Laotseu You have an interesting fork you have been maintaining and keeping up to date.
Are you at all interested in me pulling some of it into the master repo?
