### ISSUE TITLE
Prereq quest missing for a quest in guide

### ISSUE THREAD

**Issue by luisb** [Ludovicus/WoW-Pro-Guides#429]
Thousand Needles, Horde, Completeness level 1.

The quest "Bar Fight" is required for "Pirate Accuracy Increasing" but skipped in the guide. Source: http://www.wowhead.com/quest=25533/pirate-accuracy-increasing#comments by BaronYiffington (2,562 – 6·54) on 2010/11/26 (Patch 4.0.3)

**Comment by Ludovicus** [comment]
OK.  [Bar Fight] is no longer RANK|2 and is now a PRE|25518 for QID|25533.
Sorry for the delay.  I lost the notification email.
