### ISSUE TITLE
Swatter error in Gnome starter zone

### ISSUE THREAD

**Issue by Aldavor** [Ludovicus/WoW-Pro-Guides#433]
This error stops it from accepting/checking off accepted quests.

To fix I reverted the changes you made in the last commit to WowPro.lua and WowPro_Broker.lua.

(btw I don't run Recorder).

Error reports thus:
<pre>
Date: 2016-07-08 17:57:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWPro\WoWPro_Broker.lua line 1268:
   attempt to concatenate field 'title' (a nil value)
Debug:
   [C]: ?
   WoWPro\WoWPro_Broker.lua:1268: PopulateQuestLog()
   WoWPro\WoWPro_Events.lua:682:
      WoWPro\WoWPro_Events.lua:412
Locals:

AddOns:
  BlizzBugsSuck, v6.2.3.1
  Swatter, v5.21f.5579 (SanctimoniousSwamprat)
  Cursor, v6.2.3.1
  NPCScan, v6.2.4.3
  NPCScanOverlay, v6.2.4.5
  NPCScanOverlayBroker, v1.2.6
  Accountant, v6.02.60200
  Ace3, v
  AchievementsReminder, v
  ACP, v3.4.25 
  Arh, v1.5.2
  AskMrRobot, v32
  AucAdvanced, v5.21f.5579 (SanctimoniousSwamprat)
  AucFilterBasic, v5.21f.5579 (SanctimoniousSwamprat)
  AucFilterOutlier, v5.21f.5579.5459(5.21f/embedded)
  AucMatchUndercut, v5.21f.5579.5507(5.21f/embedded)
  AucStatHistogram, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatiLevel, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatPurchased, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatSales, v5.21f.5579.5476(5.21f/embedded)
  AucStatSimple, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatStdDev, v5.21f.5579 (SanctimoniousSwamprat)
  AucStatWOWEcon, v5.21f.5579.5323(5.21f/embedded)
  AucUtilAHWindowControl, v5.21f.5579.5575(5.21f/embedded)
  AucUtilAppraiser, v5.21f.5579.5545(5.21f/embedded)
  AucUtilAskPrice, v5.21f.5579.5447(5.21f/embedded)
  AucUtilAutoMagic, v5.21f.5579.5537(5.21f/embedded)
  AucUtilCompactUI, v5.21f.5579.5550(5.21f/embedded)
  AucUtilEasyBuyout, v5.21f.5579.5576(5.21f/embedded)
  AucUtilFixAH, v5.21f.5579 (SanctimoniousSwamprat)
  AucUtilItemSuggest, v5.21f.5579.5417(5.21f/embedded)
  AucUtilPriceLevel, v5.21f.5579.5535(5.21f/embedded)
  AucUtilScanButton, v5.21f.5579.5403(5.21f/embedded)
  AucUtilScanFinish, v5.21f.5579.5515(5.21f/embedded)
  AucUtilScanProgress, v5.21f.5579.4979(5.21f/embedded)
  AucUtilScanStart, v5.21f.5579.5347(5.21f/embedded)
  AucUtilSearchUI, v5.21f.5579.5556(5.21f/embedded)
  AucUtilSimpleAuction, v5.21f.5579.5531(5.21f/embedded)
  AucUtilVendMarkup, v5.21f.5579.4828(5.21f/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, v13.000
  BadBoyCCleaner, v
  BadBoyGuilded, v
  BadBoyHistory, v
  BadBoyLevels, v
  BagBrother, v
  Bagnon, v6.2.7
  Bazooka, vv2.6.1
  BeanCounter, v5.21f.5579 (SanctimoniousSwamprat)
  BittensSpellFlashKeyBindings, v60100.201503092107
  BittensSpellFlashRogue, v60200.201510100133
  BittensSpellFlashLibrary, v60100.201503092107
  BittensUtils, v60000.1.2
  ButtonForge, v0.9.40
  Configator, v5.1.DEV.396(/embedded)
  CrossRealmAssist, v0.5
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v5.21f.5579 (SanctimoniousSwamprat)
  EnchantrixBarker, v5.21f.5579 (SanctimoniousSwamprat)
  GatherMate2, v1.35.6
  Grail, v078
  GTFO, v4.38.2
  HandyNotes, vv1.4.6
  HandyNotesDraenorTreasures, v1.18a
  HealBot, v6.2.3.0
  HealBotTips, v6.2.3.0
  Incognito, v1.4.1
  Informant, v5.21f.5579 (SanctimoniousSwamprat)
  LibExtraTip, v5.12.DEV.395(/embedded)
  MasterPlanA, vA
  MogIt, v3.5.11
  MogItAccessories, v
  MoveAnything, v15.3.6
  MyBits, v
  NugComboBar, v
  OmniCC, v6.2.5
  omouse, v0.1.4
  Pawn, v1.9.31
  PetTracker, v6.2.6
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Postal, vv3.5.6
  Prat30, v3.6.12      
  Prat30Libraries, v
  QuestCompletist, v105
  Rematch, v4.4.7
  SexyMap, v2.4.26
  Skada, v1.4-33
  Skillet, v2.88
  SlideBar, v5.21f.5579 (SanctimoniousSwamprat)
  SpellFlash, v6.24.1
  SpellFlashCore, v2.1.1
  Stubby, v5.21f.5579 (SanctimoniousSwamprat)
  SuperGuildInvite, v7.5.3
  TheUndermineJournal, v4.1.20160705
  TipHelper, v5.12.DEV.389(/embedded)
  TomTom, vv60200-2.1.0
  TradeSkillMaster, vv3.3.19
  TradeSkillMasterCrafting, vv3.0.1
  TradeSkillMasterDestroying, vv3.0
  WIM, v3.7.7
  WoWPro, v6.2.4
  WoWProAchievements, v6.2.4
  WoWProDailies, v6.2.4
  WoWProLeveling, v6.2.4
  WoWProProfession, v6.2.4
  WoWProWorldEvents, v6.2.4
  BlizRuntimeLib_enUS v6.2.4.60200 <none>
  (ck=e6a)
</pre>

**Comment by Ludovicus** [comment]
Sorry about this,  that code underwent a substancial rewrite for Legion and no longer has this problem.
