### ISSUE TITLE
lua error on load

### ISSUE THREAD

**Issue by dmnkr** [Ludovicus/WoW-Pro-Guides#434]
15x WoWPro\WoWPro_Parser.lua:507: attempt to call method 'trim' (a nil value)
WoWPro\WoWPro_Parser.lua:507: in function `ParseSteps'
WoWPro\WoWPro_Parser.lua:627: in function <WoWPro\WoWPro_Parser.lua:605>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ceArchy\Libs\AceBucket-3.0\AceBucket-3.0-3.lua:118: in function `func'
...\AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0-17.lua:55: in function <...\AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals:
nil

**Comment by dmnkr** [comment]
Nevermind -- looks like the MogCollector.com addon was causing this -- after disabling it, WoW-Pro works fine.

**Comment by Ludovicus** [comment]
@dmnkr Just out of curiosity, how did MogCollector.com cause this problem?

**Comment by dmnkr** [comment]
Not entirely sure. I suspect incompatible libraries?

All I know is that when I disabled it, the error went away. If you want to play around with it, you can download MogCollector here: https://mogcollector.com/download
