### ISSUE TITLE
Modification to ITEM tag

### ISSUE THREAD

**Issue by Emmaleah** [Ludovicus/WoW-Pro-Guides#460]
When using Item tag, it prepends the item to the beginning of the note.  I would like to add "Drops" before the item and a \n after the item, so the actual note would start on a new line.
currently:
![image](https://user-images.githubusercontent.com/2212691/46563169-df404600-c8b4-11e8-96e2-69055512b42b.png)

from :Stormsong guide line 580
K Jakala the Cruel|QID|52323|QO|1|M|53.41,64.50|T|Jakala the Cruel|N|Go into the cellar. Speak with Doc Marrtens to start the event. Silver Elite to kill for loot and achievement.|RARE|ITEM|159179|RANK|2|

to become 
![image](https://user-images.githubusercontent.com/2212691/46563318-96d55800-c8b5-11e8-9afb-3a26fbe45c57.png)

**Comment by Ludovicus** [comment]
Resolved by e83438ccc8183d993d3c93021a13ea6c7d8a3703
